services:

  local_cont:
    build: ../p5_dockle/

  nginx:
    image: nginx
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - local_cont    

 
